
pipelines:
  default:
    - step:
        name: Test Python 2.7.14
        image: python:2.7.14
        caches:
          - pip
        script:
          - pip install $BITBUCKET_CLONE_DIR
          - python -m unittest discover $BITBUCKET_CLONE_DIR
    - step:
        name: Test Python 3.6
        image: python:3.6
        caches:
          - pip
        script:
          - pip install $BITBUCKET_CLONE_DIR
          - python -m unittest discover $BITBUCKET_CLONE_DIR
  tags:
    '[0-9]*.[0-9]*.[0-9]*':
      - step:
          name: Test Python 2.7.14
          image: python:2.7.14
          caches:
            - pip
          script:
            - pip install $BITBUCKET_CLONE_DIR
            - python -m unittest discover $BITBUCKET_CLONE_DIR
      - step:
          name: Test Python 3.6
          image: python:3.6
          caches:
            - pip
          script:
            - pip install $BITBUCKET_CLONE_DIR
            - python -m unittest discover $BITBUCKET_CLONE_DIR
      - step:
          name: Create Distribution
          image: python:3.6
          script:
            - cd $BITBUCKET_CLONE_DIR
            # Check tag matches version
            - CURRENT_MODULE_VERSION=`cat ./*/_metadata.py | grep -e "__version__\s*=" | sed "s/.*= u'\(.*[^']\)'.*/\1/"`
            - if [[ "$BITBUCKET_TAG" != "$CURRENT_MODULE_VERSION" ]]; then exit 1; fi
            # Generate distribution
            - python setup.py sdist
            - python setup.py bdist_wheel
          artifacts:
            - dist/**
      - step:
          name: Deploy
          #trigger: manual
          image: python:3.6
          script:
            # Check for environment variables
            - if [[ -z "$TWINE_REPOSITORY_URL" || -z "$TWINE_USERNAME" || -z "$TWINE_PASSWORD" ]]; then exit 1; fi
            # Deploy to PyPi
            - pip install twine
            - twine upload dist/*
